# Use Python 3.11 as the base image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the bot code to the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV TOKEN="8030276900:AAEeu4g2tirZjYyvxOQLhBUnFX0HAxwdwnY"

# Run the bot
CMD ["python", "bot.py"]
